// <auto-generated />
using System;
using DBModels.Hr;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DBModels.Migrations
{
    [DbContext(typeof(WarehouseContext))]
    partial class HrContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DBModels.Hr.Authority", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AbilityName")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<DateTime>("DeleteTime");

                    b.Property<DateTime>("InsertTime");

                    b.Property<int>("Mark");

                    b.Property<DateTime>("UpdateTime");

                    b.HasKey("Id");

                    b.ToTable("t_hr_authority");
                });

            modelBuilder.Entity("DBModels.Hr.Menu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DeleteTime");

                    b.Property<DateTime>("InsertTime");

                    b.Property<int>("Mark");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<DateTime>("UpdateTime");

                    b.HasKey("Id");

                    b.ToTable("t_hr_menu");
                });

            modelBuilder.Entity("DBModels.Hr.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AuthorityId");

                    b.Property<DateTime>("DeleteTime");

                    b.Property<DateTime>("InsertTime");

                    b.Property<int>("Mark");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<DateTime>("UpdateTime");

                    b.Property<long?>("UserRoleId");

                    b.HasKey("Id");

                    b.HasIndex("AuthorityId");

                    b.HasIndex("UserRoleId");

                    b.ToTable("t_hr_role");
                });

            modelBuilder.Entity("DBModels.Hr.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DeleteTime");

                    b.Property<string>("Email")
                        .HasMaxLength(30);

                    b.Property<byte[]>("Image")
                        .HasMaxLength(2000);

                    b.Property<DateTime>("InsertTime");

                    b.Property<int>("Mark");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Phone")
                        .HasMaxLength(30);

                    b.Property<bool>("Status");

                    b.Property<DateTime>("UpdateTime");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<long?>("UserRoleId");

                    b.HasKey("Id");

                    b.HasIndex("UserRoleId");

                    b.ToTable("t_hr_user");
                });

            modelBuilder.Entity("DBModels.Hr.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Mark")
                        .HasMaxLength(1);

                    b.HasKey("Id");

                    b.ToTable("t_hr_userrole");
                });

            modelBuilder.Entity("DBModels.Hr.Role", b =>
                {
                    b.HasOne("DBModels.Hr.Authority")
                        .WithMany("Role")
                        .HasForeignKey("AuthorityId");

                    b.HasOne("DBModels.Hr.UserRole")
                        .WithMany("Roles")
                        .HasForeignKey("UserRoleId");
                });

            modelBuilder.Entity("DBModels.Hr.User", b =>
                {
                    b.HasOne("DBModels.Hr.UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId");
                });
#pragma warning restore 612, 618
        }
    }
}
